### ISSUE TITLE
Security Improvement: One Time Secret for each link in the database

### ISSUE THREAD

**Issue by holzhannes** [syseleven/shared-secrets#6]
What I can see so far is that the encrypted content is always inside the link an the database on the server is just preventing the decryption (not making it impossible) of links once they are viewed once. Therefore if you just edit the database (delete a entry) it would be possible to decrypt the Link again if have the private pgp key.

**My Idea**

To Improve the Security of the System it would be good to store an individual ID and/or additional one-time-encryption-secret for each link in the database which is needed as a second factor to decrypt the link content and only known by the server.
After retrieving the link the one-time-encryption-secret just has to be deleted. The one-time-encryption-secret could also be used to give the link a lifetime, because after deleting it decrypting the link would be impossible.

**Comment by yahesh** [comment]
Hi @holzhannes, first of all, thanks for your input.

We thought about other ways of securing shared secrets as well but always felt that breaking other properties of the solution just isn't worth it. E.g., implementing the solution you described would break the following parts of the current solution:
* You wouldn't be able to generate secret-sharing URLs offline without having to interact with the server. Currently you can generate secret-sharing links just by downloading the corresponding public key and doing everything else on the command line. You only have to interact with the server when retrieving an encrypted secret.
* Currently, the storage requirements of the database only rely on the number of retrieved secrets and not on the number of generated secret-sharing links. Switching to a mechanism where you have to store a value for each generated (and not yet retrieved) secret-sharing link would break this correlation.
* This service is meant to be used with customers who aren't able to use E2E encryption schemes. But, as these are customers we chose a solution that values availability of data a bit higher than confidentiality. You're right that you could restore a secret if you know the secret and (at the same time) have access to the secret-sharing link that contains the encrypted secret. In the case where you may need to possibility to support an emergency-restore of a secret, this is simplified by the given structure. To have an additional layer of protection to prevent such a decryption by potentially malicious server admins we added the additional client-side encryption some time ago (which we assume is a better solution to the remaining problem of potential second retrievals).

Also, there additionally is a shortcoming of the proposed solution: At the moment, when the database is lost - in theory - all secret-sharing links could be decrypted again. In reality, the easiest way to prevent second retrievals in such a case would be to just change the used keypair. In your solution it would be vital to have backups of the database, thus "deleted" information could be recovered from those backups. Also, "deletes" in databases typically don't purge the data but rather mark them as purgable/overwritable. So, the "deletion" of that information wouldn't be all too secure.

That's why, in conclusion, I'd prefer not to go forward with the proposed solution.

**Comment by yahesh** [comment]
Closing this as **wontfix**.
